import type { Appointment, Claim, Clinic, Employee, HealthCoreDataset, Patient } from "../main";

export const sampleClinics: Clinic[] = [
  {
    clinicId: "CLN-US-AUS-01",
    clinicName: "HealthCore Austin Central",
    country: "US",
    region: "Texas",
    ehrPlatform: "US_EHR",
    departmentOwner: "Dr. Marcus Reid",
    extendedHours: true,
    bilingualStaff: true,
  },
  {
    clinicId: "CLN-US-MIA-01",
    clinicName: "HealthCore Miami Beach",
    country: "US",
    region: "Florida",
    ehrPlatform: "US_EHR",
    departmentOwner: "Dr. Marcus Reid",
    extendedHours: true,
    bilingualStaff: true,
  },
  {
    clinicId: "CLN-UK-LON-01",
    clinicName: "HealthCore London City",
    country: "UK",
    region: "London",
    ehrPlatform: "UK_EHR",
    departmentOwner: "Dr. Marcus Reid",
    extendedHours: false,
    bilingualStaff: false,
  },
];

export const samplePatients: Patient[] = [
  {
    patientId: "PAT-001",
    fullName: "Ana Rivera",
    country: "US",
    dateOfBirth: "1989-03-15",
    phone: "+1-512-555-0101",
    email: "ana.rivera@example.com",
    hipaaConsent: true,
    gdprConsent: false,
  },
  {
    patientId: "PAT-002",
    fullName: "Liam Carter",
    country: "UK",
    dateOfBirth: "1978-11-02",
    phone: "+44-20-5555-0102",
    email: "liam.carter@example.co.uk",
    hipaaConsent: false,
    gdprConsent: true,
  },
  {
    patientId: "PAT-003",
    fullName: "Noah Bennett",
    country: "US",
    dateOfBirth: "1995-07-22",
    phone: "+1-305-555-0103",
    email: "noah.bennett@example.com",
    hipaaConsent: true,
    gdprConsent: false,
  },
];

export const sampleAppointments: Appointment[] = [
  {
    appointmentId: "APT-001",
    patientId: "PAT-001",
    clinicId: "CLN-US-AUS-01",
    country: "US",
    scheduledAt: "2026-08-18T09:30:00Z",
    attended: true,
    bookingChannel: "Phone",
    reminderStatus: "Confirmed",
    noShowRiskScore: 0.18,
    patientSatisfactionScore: 5,
  },
  {
    appointmentId: "APT-002",
    patientId: "PAT-002",
    clinicId: "CLN-UK-LON-01",
    country: "UK",
    scheduledAt: "2026-08-19T13:00:00Z",
    attended: false,
    bookingChannel: "FrontDesk",
    reminderStatus: "Sent",
    noShowRiskScore: 0.82,
    patientSatisfactionScore: null,
  },
  {
    appointmentId: "APT-003",
    patientId: "PAT-003",
    clinicId: "CLN-US-MIA-01",
    country: "US",
    scheduledAt: "2026-08-21T15:15:00Z",
    attended: true,
    bookingChannel: "Phone",
    reminderStatus: "Confirmed",
    noShowRiskScore: 0.36,
    patientSatisfactionScore: 4,
  },
  {
    appointmentId: "APT-004",
    patientId: "PAT-001",
    clinicId: "CLN-US-AUS-01",
    country: "US",
    scheduledAt: "2026-08-22T10:00:00Z",
    attended: false,
    bookingChannel: "Phone",
    reminderStatus: "NotSent",
    noShowRiskScore: 0.73,
    patientSatisfactionScore: null,
  },
];

export const sampleClaims: Claim[] = [
  {
    claimId: "CLM-001",
    appointmentId: "APT-001",
    country: "US",
    payerType: "CommercialInsurance",
    amountUsd: 180,
    status: "Paid",
    denialReason: null,
  },
  {
    claimId: "CLM-002",
    appointmentId: "APT-002",
    country: "UK",
    payerType: "PrivatePay",
    amountUsd: 240,
    status: "Denied",
    denialReason: "Missing coding detail",
  },
  {
    claimId: "CLM-003",
    appointmentId: "APT-003",
    country: "US",
    payerType: "Medicaid",
    amountUsd: 130,
    status: "Submitted",
    denialReason: null,
  },
  {
    claimId: "CLM-004",
    appointmentId: "APT-004",
    country: "US",
    payerType: "Medicare",
    amountUsd: 210,
    status: "Pending",
    denialReason: null,
  },
];

export const sampleEmployees: Employee[] = [
  {
    employeeId: "EMP-001",
    fullName: "Dr. Maya Chen",
    country: "US",
    roleType: "Physician",
    locationName: "HealthCore Austin Central",
    timeToHireDays: 52,
    cmeHoursCompleted: 18,
    cmeHoursRequired: 24,
    licenseExpiryDate: "2026-10-15",
  },
  {
    employeeId: "EMP-002",
    fullName: "Olivia Scott",
    country: "UK",
    roleType: "Nurse",
    locationName: "HealthCore London City",
    timeToHireDays: 41,
    cmeHoursCompleted: 20,
    cmeHoursRequired: 20,
    licenseExpiryDate: "2027-04-30",
  },
  {
    employeeId: "EMP-003",
    fullName: "James Walker",
    country: "US",
    roleType: "Technology",
    locationName: "HealthCore Austin Central",
    timeToHireDays: 33,
    cmeHoursCompleted: 0,
    cmeHoursRequired: 1,
    licenseExpiryDate: null,
  },
];

export const sampleDataset: HealthCoreDataset = {
  clinics: sampleClinics,
  patients: samplePatients,
  appointments: sampleAppointments,
  claims: sampleClaims,
  employees: sampleEmployees,
};
